apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: giantswarm-critical
value: 1000000000
---
apiVersion: v1
kind: Namespace
metadata:
  name: giantswarm
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: appcatalog
  namespace: giantswarm
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: appcatalog_cluster-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: appcatalog
  namespace: giantswarm
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-operator-unique
  namespace: giantswarm
data:
  config.yaml: "server:\n  enable:\n    debug:\n      server: true\n  listen:\n    address:
    'http://0.0.0.0:8000'\nservice:\n  app:\n    unique: true\n  chart:\n    webhookAuthToken:
    '83W2O4BRzVbwp*3KjVrj8&1Mz68%B&vA'\n    webhookBaseURL: 'http://app-operator-unique.giantswarm.svc.cluster.local:8000'\n
    \ helm:\n    http:\n      clientTimeout: '5s'\n  image:\n    registry: 'quay.io'
    \n  kubernetes:\n    incluster: true\n"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-operator
  name: app-operator
  namespace: giantswarm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-operator
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: app-operator
      name: app-operator
      namespace: giantswarm
    spec:
      containers:
      - args:
        - daemon
        - --config.dirs=/var/run/app-operator/configmap/
        - --config.files=config
        image: quay.io/giantswarm/app-operator:2.8.0
        name: app-operator
        volumeMounts:
        - mountPath: /var/run/app-operator/configmap/
          name: app-operator-configmap
      serviceAccount: appcatalog
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: config.yaml
            path: config.yaml
          name: app-operator-unique
        name: app-operator-configmap
      tolerations:
      - effect: NoExecute
        key: node.kubernetes.io/not-ready
        operator: Exists
        tolerationSeconds: 300
      - effect: NoExecute
        key: node.kubernetes.io/unreachable
        operator: Exists
        tolerationSeconds: 300